### ISSUE TITLE
Help me to understand code

### ISSUE THREAD

**Issue by chetandhembre** [mafintosh/speedometer#4]
first of all I am sorry to ask you such naive question.. But after reading you code my mind is spinning.
Can you tell me which algorithm you used (or you developed your own) ? so that I can go and learn more about it 

BTW I am great fan of you modules.
Thanks you !!

**Comment by mafintosh** [comment]
Hi - thanks for taking the time to read this code.

It uses a regular sliding window that is updated (per default every 1/4th second) Basically there is a an array that has size `buffer-this-many-seconds * 4` (the default is 5s) and two pointers `top` and `btm` that points to the newest entry in this buffer and the oldest one. Every 1/4th second the `top` pointer is incremented and if it is bigger than the array is it reset to 0. When `top === btm` we increment `btm` as well (as the oldest entry is now outdated).

When ever you update the speedometer with a delta value we increment `array[top]` with this value and when the `top` pointer is incremented we copy the value to the new top entry.

To calculate the speed we now just need to `(array[top] - array[btm]) / 5` since that gives us the delta speed in the last 5s.

Hope this was helpful otherwise let me know :)

**Comment by chetandhembre** [comment]
Wow !! 
Thanks !!!
I just took paper-pen and started executing every step for data. Above explanation helps me a lot.

I have one question..
As per my understanding 
array[top] will be latest delta value and array[btm] will be (previous delta value || 0) always. 
Is there case where we will have new scenario ?

**Comment by mafintosh** [comment]
No that should always be the case

**Comment by chetandhembre** [comment]
then why not just store previous array[top] in some variable and next time just do ```(new array[top] - previous[top]) / 5```

wont it works ? Am I missing some case here ?

**Comment by mafintosh** [comment]
ah i misunderstood what you said. no array[btm] is always the *oldest* value. the array might contain a bunch of values and top points to the newest one and btm points to the oldest one.

**Comment by chetandhembre** [comment]
Gotcha!!
So case I mention above will fails when two or more times we call ```speed(data.length)``` before completion of  buffer seconds ```(var speed = speedometer(seconds))```. 
In this case ```btm``` wont change but ```top``` will change.
Am I right ?

**Comment by chetandhembre** [comment]
I guess I understood basic of algorithm .. And I can visualize how can array[btm] oldest value in buffer. Basically it will store delta at ```new Date().getTime() - buffered_seconds * 1000``` (I can say this roughly). This case can occurs in many scenario.

Thanks you for quick response to issue.

**Comment by mafintosh** [comment]
Great! No problem.

**Comment by JaosnHsieh** [comment]
Thanks for the explanation! I have one more question about the algorithm.

Does the way the speed reduces give us some more useful info or why we prefer to reduces the speed in this way instead linear?

For example, below code set the `buffer to 10s and add 1 byte at begining`

```javascript
var speedometer = require('speedometer');
let count = 0;
var speed = speedometer(10);
speed(1);

let previous = speed(0);
console.log(`$ 0 s passed, speed ${speed(0)}\n`);

setInterval(() => {
  const current = speed(0);
  console.log(
    `$ ${++count} s passed, current speed ${current.toFixed(
      2,
    )}, previous - current speed ${(previous - current).toFixed(2)}`,
  );
  previous = speed(0);
}, 1000);

```

I was expecting the speed will be reduced in linear shape such as below table


| 0s | 1s | 2s | 3s | ... | 9s | 10s |
| ------------- | ------------- |
| 1 byte/s  | 0.9 byte/s  | 0.8 byte/s | 0.7 byte/s | 0.1 byte/s | 0 byte/s


but now the speed reduced as below

```
$ buffer.length < resolution is false. value is 0.8 from (1 - 0) * 4 / 5. (top - btm) * resolution / buffer.length
$ 1 s passed, current speed 0.80, previous - current speed 0.20
$ buffer.length < resolution is false. value is 0.8 from (1 - 0) * 4 / 5. (top - btm) * resolution / buffer.length
$ buffer.length < resolution is false. value is 0.4444444444444444 from (1 - 0) * 4 / 9. (top - btm) * resolution / buffer.length
$ 2 s passed, current speed 0.44, previous - current speed 0.36
$ buffer.length < resolution is false. value is 0.4444444444444444 from (1 - 0) * 4 / 9. (top - btm) * resolution / buffer.length
$ buffer.length < resolution is false. value is 0.3076923076923077 from (1 - 0) * 4 / 13. (top - btm) * resolution / buffer.length
$ 3 s passed, current speed 0.31, previous - current speed 0.14
$ buffer.length < resolution is false. value is 0.3076923076923077 from (1 - 0) * 4 / 13. (top - btm) * resolution / buffer.length
$ buffer.length < resolution is false. value is 0.23529411764705882 from (1 - 0) * 4 / 17. (top - btm) * resolution / buffer.length
$ 4 s passed, current speed 0.24, previous - current speed 0.07
$ buffer.length < resolution is false. value is 0.23529411764705882 from (1 - 0) * 4 / 17. (top - btm) * resolution / buffer.length
$ buffer.length < resolution is false. value is 0.19047619047619047 from (1 - 0) * 4 / 21. (top - btm) * resolution / buffer.length
$ 5 s passed, current speed 0.19, previous - current speed 0.04
$ buffer.length < resolution is false. value is 0.19047619047619047 from (1 - 0) * 4 / 21. (top - btm) * resolution / buffer.length
```
