### ISSUE TITLE
[Question] Measure calls in 24h

### ISSUE THREAD

**Issue by Kikobeats** [mafintosh/speedometer#6]
I'm trying to measure API calls in 24h.

Do you think that this could be a good approach for that?

``` js
var ONE_DAY_SECONDS = 86400
var speedometer = require('speedometer')(ONE_DAY_SECONDS)
```

**Comment by afanasy** [comment]
@Kikobeats The internal buffer size will be too big, I think it is not optimized for long intervals.

**Comment by Kikobeats** [comment]
Good point, finally I didn't use it but could be great to include into docs
